/* Pure production helper regression. Safe in SQF-VM; no campaign/world mutation. */
private _reserve = compile preprocessFileLineNumbers "functions/command/fn_intelOrderReserveSlot.sqf";
private _spec = compile preprocessFileLineNumbers "functions/command/fn_intelOrderTaskSpec.sqf";
private _ids = compile preprocessFileLineNumbers "functions/core/fn_resetOrderTaskIds.sqf";
private _checks = 0;
private _assert = {params ["_ok","_label"]; if (!_ok) then {throw _label;}; _checks = _checks + 1;};
private _live = ["ord1",1,"ACCEPTED","RTB","RF1",[["taskId","ord1_task"],["destPos",[100,200,0]],["destLabel","HQ"],["purpose","INTEL"]],[["note","Report"]]];
private _terminal = ["ord2",2,"COMPLETED","HOLD","RF2",[["taskId","ord2_task"]],[]];
private _issued = ["ord3",3,"ISSUED","HOLD","RF3",[],[]];
private _source = [_live,_terminal,_issued];
private _before = str _source;
private _r = [_source,3,""] call _reserve;
[(_r select 0) && {(_r select 1) isEqualTo [_live,_issued]} && {(_r select 2) isEqualTo [_terminal]},"evict terminal, retain old live"] call _assert;
[(str _source) isEqualTo _before,"admission must not mutate input"] call _assert;
_r = [[_live,_issued],2,""] call _reserve;
[!(_r select 0) && {(_r select 1) isEqualTo [_live,_issued]} && {(_r select 2) isEqualTo []},"full live capacity refusal preserves all"] call _assert;
_r = [[_live,_terminal],2,"ord2"] call _reserve;
[!(_r select 0),"pending-closeout terminal reference protected"] call _assert;
_r = [[_live],3,""] call _reserve;
[(_r select 0) && {(_r select 2) isEqualTo []},"spare capacity has no eviction"] call _assert;
_r = [[_terminal,_terminal,_live],2,""] call _reserve;
[(_r select 0) && {(_r select 1) isEqualTo [_live]} && {count (_r select 2) == 2},"over-cap history reduced before reservation"] call _assert;
_r = [[[],_live],2,""] call _reserve;
[!(_r select 0),"unknown record cannot be silently evicted"] call _assert;
private _collected = [[_live,_terminal,_live,[],["bad",0,"ACCEPTED","RTB","RF",[["taskId",7]]]]] call _ids;
[_collected isEqualTo ["ord1_task","ord2_task"],"reset collects live and terminal IDs once and ignores malformed IDs"] call _assert;
private _view = [_live] call _spec;
[count _view == 6 && {(_view select 0) isEqualTo "ord1_task"} && {(_view select 1) isEqualTo "RF1"},"RTB uses persisted identity/group"] call _assert;
[(_view select 4) isEqualTo [100,200,0] && {(_view select 5) isEqualTo "MOVE"},"RTB uses saved destination"] call _assert;
[(_view select 3) find "Intel Debrief" >= 0,"RTB preserves debrief instruction"] call _assert;
[([_live] call _spec) isEqualTo _view && {(str _source) isEqualTo _before},"view reconstruction is repeatable and read-only"] call _assert;
private _hold = ["hold1",0,"ACCEPTED","HOLD","RF2",[["taskId","hold1_task"],["holdPos",[10,20]]],[]];
_view = [_hold] call _spec;
[(_view select 4) isEqualTo [10,20,0] && {(_view select 5) isEqualTo "HOLD"},"HOLD restores original position with normalized altitude"] call _assert;
[_hold select 5 isEqualTo [["taskId","hold1_task"],["holdPos",[10,20]]],"normalization cannot alter saved destination"] call _assert;
[[ _terminal ] call _spec isEqualTo [],"terminal order is never recreated"] call _assert;
[[ _issued ] call _spec isEqualTo [],"unaccepted order is never recreated"] call _assert;
private _bad = +_live;
_bad set [5,[["taskId","ord1_task"],["destPos",["bad",2]]]];
[[ _bad ] call _spec isEqualTo [],"invalid saved destination rejects safely"] call _assert;
diag_log format ["[ARC][COMMAND_TEST] ALL_PASS checks=%1",_checks];
true
