/* Execute the production pure evaluator, including a real clock rebase. */
private _evaluate = compile preprocessFileLineNumbers "functions/core/fn_leadDecay.sqf";
private _rebase = compile preprocessFileLineNumbers "functions/core/fn_stateRebaseClock.sqf";
private _passes = 0;
private _assert = {
    params ["_condition", "_label"];
    if (!_condition) then {throw format ["LEAD FAIL: %1", _label]};
    _passes = _passes + 1;
    diag_log format ["LEAD PASS: %1",_label];
};
private _lead = ["L1","IED","Intel",[10,20,0],0.8,0,1200,"","","","",[["origin","FIELD"],["leadDecayV",1],["leadDecayStrength",0.8],["leadDecayStartedAt",0],["leadDecayTtl",1200]]];
private _half = [_lead,600] call _evaluate;
[abs ((_half select 4) - 0.56) < 0.0001,"half-life strength is 0.56"] call _assert;
private _repeat = [_half,600] call _evaluate;
[_repeat isEqualTo _half,"same-age evaluation is idempotent"] call _assert;
private _frequent = +_lead;
for "_t" from 10 to 900 step 10 do {_frequent = [_frequent,_t] call _evaluate};
private _single = [_lead,900] call _evaluate;
[abs ((_frequent select 4) - (_single select 4)) < 0.0001,"90 evaluations match one evaluation"] call _assert;
[(_lead select 4) == 0.8,"input record remains unchanged"] call _assert;
[(count _frequent) == 12,"12-field contract retained"] call _assert;
[((_frequent select 11) select 0) isEqualTo ["origin","FIELD"],"unrelated origin metadata retained"] call _assert;
private _legacy = ["L2","IED","Legacy",[],0.4,0,1200,"","","","",[]];
private _adopted = [_legacy,600] call _evaluate;
[(_adopted select 4) == 0.4,"legacy confidence is adopted without a discontinuity"] call _assert;
private _adoptedAgain = [_adopted,600] call _evaluate;
[_adoptedAgain isEqualTo _adopted,"legacy migration occurs once"] call _assert;
private _never = +_lead;
_never set [6,-1];
[([_never,900] call _evaluate) isEqualTo _never,"no-expiry lead remains unchanged"] call _assert;
private _state = [["leadPool",[_half]]];
private _restored = [_state,600,30] call _rebase;
private _loadedLead = ((_restored select 0) select 1) select 0;
private _loadedEval = [_loadedLead,330] call _evaluate;
[abs ((_loadedEval select 4) - (_single select 4)) < 0.0001,"restart preserves elapsed confidence decay"] call _assert;
private _expiry = [_lead,1200] call _evaluate;
[abs ((_expiry select 4) - 0.32) < 0.0001,"expiry floor follows original confidence"] call _assert;
private _low = +_lead;
_low set [4,0.1];
_low set [11,[["leadDecayV",1],["leadDecayStrength",0.1],["leadDecayStartedAt",0],["leadDecayTtl",1200]]];
private _lowHalf = [_low,600] call _evaluate;
[abs ((_lowHalf select 4) - 0.075) < 0.0001,"floor-binding first evaluation preserves existing balancing"] call _assert;
diag_log format ["LEAD REGRESSION COMPLETE: %1 PASS",_passes];
